### PR TITLE
fix compilation errors

### PR DESCRIPTION
**Pull request by Moon1102**
Fix compilation errors at Rust version 1.78.

Description of changes:

1. I think ```rusttype``` is mainly to introduce the default font, but in fact to pass is ```ab_glyph::Font```, so I use ```ab_glyph::FontArc```.

2. ```draw_text_mut``` method needs ```ab_glyph::PxScale```, so use ```ab_glyph::PxScale``` instead of ```rusttype::Scale```, there is no place to use rusttype, we can consider to remove it.

3. fixed the problem of From<f32>, directly use ```core::convert::Into``` on the line, so we can remove ```conv``` lib

It now works well with Rust 1.78 after these changes.

### CODE REVIEW

**Comment by alabulei1** [comment]
Hello, I am a [code review bot](https://github.com/flows-network/github-pr-summary/) on [flows.network](https://flows.network/).

It could take a few minutes for me to analyze this PR. Relax, grab a cup of coffee and check back later. Thanks!

**Comment by hydai** [comment]
Hi @Moon1102 
Please sign your commits with DCO. Ref: https://www.secondstate.io/articles/dco/

**Comment by yanghaku** [comment]
@Moon1102  Thanks for your PR! I think this is a perfect solution to  #6, it does not change the interface and also removes the redundancy dependencies.
